### PR TITLE
Completing support for Haiku

### PR DESCRIPTION
**Pull request by khallebal**
Hi @tsujan , here is a PR that completes support for Haiku.
Thanks for reviewing.

### CODE REVIEW

**Comment by khallebal** [comment]
Thanks for the heads up, it's fixed now.

**Comment by tsujan** [comment]
@khallebal Thank you very much!

**Comment by khallebal** [comment]
@tsujan You're welcome

**Comment by tsujan** [comment]
It's exciting to support Haiku OS. Since I tried its early versions on VirtualBox years ago, I thought it was impossible that one of my apps could work on it.

Please keep on the good work and, if needed, update it!

**Comment by khallebal** [comment]
> Please keep on the good work and, if needed, update it!

I will, ...just a quick note, unlike featherpad for some reason feathernotes does not pick the system icons (toolbar and menus), is it because it' not yet implemented?, it's not all that important, it's just that all other Qt apps in haiku use system icons thanks to the qthaikuplugins.

**Pull request merged**
