### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by shlyakpavel**
image
Have fun 😆 
P. S. Do not merge. Translations do not work, etc.. Should also test for platform-specific bugs
P. P. S. Some technical info: qmake, msvc 2017 64bit, qt 5.13.0

### CODE REVIEW

**Comment by shlyakpavel** [comment]
An important note on global defines: please be careful with them. For example, Microsoft standard library has an enum called `DATADIR`. Global redefine makes it feel *crazy*

**Comment by shlyakpavel** [comment]
@tsujan what kind of syntax to you prefer to use?
I can use both `#if not defined (abc) ` and `#ifndef abc`

**Comment by tsujan** [comment]
This one is purely Qt-based -- no Hunspell dependency :)

> what kind of syntax to you prefer to use?

I think `#if not defined (abc)` is cleaner; isn't it?

**Comment by shlyakpavel** [comment]
Everything seems to be fine now. Ready for merge

**Comment by tsujan** [comment]
Thank you very much for your nice contributions!

**Comment by tsujan** [comment]
Oh, I wanted to ask about the tray icon. Does it work fine under Windows too?

**Comment by shlyakpavel** [comment]
> Does it work fine under Windows too?

Of course. It's Qt, you know :)

**Comment by tsujan** [comment]
Very good!

> Of course. It's Qt, you know :)

Yes, it's Qt... but that's *MS Windows* ;)

**Pull request merged**
