### PR TITLE
i18n: Add Polish translation and plurals handling | fix typo

### PR DESCRIPTION
**Pull request by m4sk1n**

### CODE REVIEW

**Comment by tsujan** [comment]
Thank you very much for `feathernotes_pl.ts` and also, for correcting that typo of mine ("sellect")!

Using 3 translations for replacements (No Replacement, One Replacement and "%1 Replacements) was intentional -- to avoid `(s)`. I've done the same thing in FeatherPad. It can be seen as a style ;)

I'll add `feathernotes_pl.ts` separately in a commit soon -- should add a Translators tab to the About dialog too :)

**Comment by m4sk1n** [comment]
@tsujan, seems like it’s possible to make _en.ts file and use it only for plurals handling, but I don’t know how to do it…

**Comment by tsujan** [comment]
Interesting! I tested it without translations but will investigate it.

**Comment by tsujan** [comment]
I added your translation and fix in https://github.com/tsujan/FeatherNotes/commit/eb2694fe353075349ad8b812e3b83a25acb364c4 . It also includes a Translators tab for About dialog.

I copy-pasted your "replacement" translations from FeatherPad and would be grateful if you check them. It seems to me that different Polish translations are possible here but I don't know which is better. Sorry if copy-pasting was a terrible idea ;)

I also investigated the case of `(s)` and it was exactly as you told. However, since I've separated all 3 possible cases from each other (0, 1, and > 1), the current old-fashioned code seems more elegant to me than Qt's plural form feature.

**Pull request closed without merging**
