### PR TITLE
Mac installation support

### PR DESCRIPTION
**Pull request by shlyakpavel**
Mac compiles and installs fine. Translations are also fine.
Fixes https://github.com/tsujan/FeatherNotes/issues/44

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks a lot!

Is the macOS support complete now? If so, I'll add a line to README.

**Comment by shlyakpavel** [comment]
@tsujan both FeatherPad and FeatherNotes lack app icon on Mac. That's the only issue for now.
image
In my opinion, it's not crucial so you can add a link :)

**Comment by tsujan** [comment]
I'll announce the macOS support in both README files.

I vaguely remember that you'd found a solution. I'll google for "macOS Qt project app icon" later.

**Comment by tsujan** [comment]
And I agree that it isn't crucial.

**Comment by shlyakpavel** [comment]
> I'll google for "macOS Qt project app icon" later.

No need to
There is official documentation that works fine
http://doc.qt.io/qt-5/appicon.html#setting-the-application-icon-on-macos
However, I personally *do not like* the idea of adding rasterized icons to git. I've found a way to process svg, but as I've already mentioned it needs scripting.

**Pull request merged**
