### PR TITLE
Code improvements

### PR DESCRIPTION
**Pull request by shlyakpavel**
Hello again. This project seems to have even better code than the FeatherPad has. Still I hove found some places to change. I really hope you enjoy it :)
Thanks for the great project and have a nice day!

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks again for fixing problems/mistakes! I really appreciate your skill in finding and correcting them.

By a glance at your patch, I can see that it's very good. However,

(1) Your patch reminded me that I hadn't replaced `QRegExp` with `QRegularExpression` in FeatherNotes. I should do it soon, in the next commit.

(2) As for removing double backslashes with `R"()"` in c++11, it's a nice idea and I'll do so in FeatherNotes as you suggested. But I prefer not to touch FeatherPad's regex strings for now because a simple mistake could have bad consequences.

(3) I always prefer to use `break;` after `return`; you could see it like a personal habit or style ;) I also sometimes check for nullity before deletion as an old habit.

So, I'll use your good patch in the next commit and give you the credit for it, as I did in FeatherPad.

> This project seems to have even better code than the FeatherPad has

They're very different from each other but both have a similar story: they were written in GTK2, then in GTK3, then completely rewritten in Qt4 and, finally, modified for Qt5. During these phases, I added a lot of features, fixed many problems and, sometimes, changed the code structure. Things like `0` or `NULL` instead of `nullptr` or not passing `QString` by reference in some places are remainders of old codes.

**Please keep up the good work in LXQt too! It's nice to have your work there.**

**Comment by shlyakpavel** [comment]
> As for removing double backslashes with R"()" in c++11, it's a nice idea and I'll do so in FeatherNotes as you suggested. But I prefer not to touch FeatherPad's regex strings for now because a simple mistake could have bad consequences.

That is actually simple to be automated :)
It is **extremely** easy to make mistakes while escaping a regular expression. Thus, I would still prefer to switch to raw strings wherever possible...

**Comment by tsujan** [comment]
> That is actually simple to be automated :)

If I implement [regex search/replacement](https://github.com/tsujan/FeatherPad/issues/210) in FeatherPad, I should use that `R`. At some point, I'll put it everywhere needed but should do that with care -- the switch from `QRegExp` to `QRegularExpression` in FeatherPad was painful enough.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherNotes/commit/c7ce64e1877429653355ed03e3565c9da1d088e0

Qt's `lupdate` is confused by raw literals (because of https://bugreports.qt.io/browse/QTBUG-42736) but without causing any problem.

**Pull request closed without merging**
