### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by HelixBot**
Translations update from [Weblate](https://weblate.lxqt.org/projects/tsujan/feathernotes/) for tsujan/FeatherNotes.

### CODE REVIEW

**Comment by tsujan** [comment]
@yarons Thanks!

**Comment by yarons** [comment]
My pleasure! There's still a long way to go :) Hoping to finish the localization soon…

**Comment by tsujan** [comment]
@yarons  Take your time.

**Comment by yarons** [comment]
@tsujan Nah, I already completed the entire translation today, no more time to take :)

**Comment by tsujan** [comment]
I appreciate it. I know how hard translations can be.

**Comment by yarons** [comment]
Thank you so much, keep up the good work :)

**Pull request merged**
